language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed tonerolima/udagram-api-feed:3
  - docker tag udagram-api-user tonerolima/udagram-api-user:3
  - docker tag udagram-frontend tonerolima/udagram-frontend:3
  - docker tag udagram-reverseproxy tonerolima/udagram-reverseproxy:4

after_success:
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tonerolima/udagram-api-feed:3
  - docker push tonerolima/udagram-api-user:3
  - docker push tonerolima/udagram-frontend:3
  - docker push tonerolima/udagram-reverseproxy:5
