apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverse-proxy
  labels:
    app: udagram-reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverse-proxy
  template:
    metadata:
      labels:
        app: udagram-reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: tonerolima/udagram-reverseproxy:9
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 10m
